//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace NB00M
{
    public partial class CodiciCompetenzeADC
    {
        #region Primitive Properties
    string pippo;
        public virtual int ID
        {
            get;
            set;
        }
    
        public virtual string CodiceBanca
        {
            get;
            set;
        }
    
        public virtual string Codice
        {
            get;
            set;
        }
    
        public virtual string Descrizione
        {
            get;
            set;
        }
    
        public virtual int LivelloCompetenza
        {
            get;
            set;
        }
    
        public virtual string AlertMail
        {
            get;
            set;
        }
    
        public virtual int ID_Iter
        {
            get;
            set;
        }
    
        public virtual string LetteraAbil
        {
            get;
            set;
        }
    
        public virtual Nullable<bool> SoloStorico
        {
            get;
            set;
        }
    
        public virtual string CodiceAdded
        {
            get;
            set;
        }
    
        public virtual Nullable<int> LivelloCompetenzaAdded
        {
            get;
            set;
        }
    
        public virtual string LetteraAbilAdded
        {
            get;
            set;
        }

        #endregion

    }
}
